### ISSUE TITLE
White space

### ISSUE THREAD

**Issue by penx** [penx/govuk-react#173]
All components should have default margin-bottom such that when they are used together they space themselves out automatically.

`marginBottom` should be an optional prop on these components that uses a number 0 to 9 representing the spacing units listed at:

https://govuk-design-system-production.cloudapps.digital/styles/spacing/

(to discuss - `:last-child` components should always have a margin bottom of 0?)

We will likely use Cosmos' implementation as a guide for handling this.

**Comment by penx** [comment]
<img width="634" alt="screen shot 2018-03-26 at 10 21 54" src="https://user-images.githubusercontent.com/1027024/37898003-8c59fbb0-30df-11e8-8dc9-0195b062e47a.png">

**Comment by penx** [comment]
Some thinking from Nick Colley on Slack:

> I think a higher order component would be good for that
If you stick to a unidirectional vertical spacing that'll make it easier too.
This is an interesting approach: https://github.com/jxnblk/styled-system
You could do something in the same spirit with the components allowing for a spacing prop, that then defers to the spacing utility classes under the hood.

**Comment by penx** [comment]
Potential approach:

- all components have 0 margin top and bottom but when we export them we wrap them with a higher order component
- HOC takes the default marginBottom as a config setting and allows marginBottom to be passed in as a prop
- this means the HOC deals with all the margin stuff and the parent component is only responsible for setting the default. We can then add other features such as margin top, or a direct pixel override in the future to all components by only editing the HOC or even refactor the whole spacing by just editing the HOC

**Comment by penx** [comment]
Optional:

Either: 

- components/HOC take a `disableLastChildMargin` prop that is a boolean defaults to false

or

- components/HOC take a `lastChildMargin` prop that is a boolean defaults to false

**Comment by penx** [comment]
@siddharthkp we've been thinking about the white space issue I discussed with you a lot 🙂 I think the above 2 posts should solve it for us, perhaps you'd find it useful

**Comment by siddharthkp** [comment]
@landitus, I used your method here 😄

**Comment by penx** [comment]
Related thread
