### ISSUE TITLE
Discussion: use emotion, styled-components or Glamorous?

### ISSUE THREAD

**Issue by penx** [penx/govuk-react#219]
To discuss whether to use [emotion](https://emotion.sh/), [styled-components](https://www.styled-components.com/) or [Glamorous](https://glamorous.rocks/)

Some points:

- [glamor](https://github.com/threepointone/glamor) has:
  - not had any activity in master in the last 7 months
  - 58 open issues and 17 open PRs
- the following have caused us issues:
  - https://github.com/paypal/glamorous/issues/396
  - https://github.com/threepointone/glamor/issues/374
  - https://github.com/threepointone/glamor/issues/79
- debatably styled-components has a more active community
- alternatively emotion supports a similar syntax to Glamorous

> I need a blog post from you. "Why would I ever want to use glamorous if there's emotion?"

https://twitter.com/kentcdodds/status/882670388106448897

In the long term, it looks like [ISTF](https://github.com/cssinjs/istf-spec) will be the best approach

**Comment by penx** [comment]
I would suggest if we change this we should bump from `0.1.x` to `0.2.x`

**Comment by stevesims** [comment]
ISTF is interesting, and could be sensible long-term for a library to use, however it's not had a commit made or an issue filed (or even commented on) since November - so it may well be dead

**Comment by penx** [comment]
It's not dead, that project's just the spec, implementations are going on here:

https://github.com/styled-components/styled-components/issues/1617
https://github.com/kitten/sweetsour

**Comment by stevesims** [comment]
cool - good to see :grin:
that's a tick in favour of styled-components then...

**Comment by penx** [comment]
I think emotion is also planning to use ISTF, I think via a shared parsing engine (sweetsour) with styled-components, but can't find a reference to this right now

**Comment by penx** [comment]
> yes, also emotion will use istf in the future
https://github.com/cssinjs/react-jss/issues/109#issuecomment-314505861

> preprocessing is going to be implemented in v3 using a "core library" (which might be shared with emotion and others)
https://github.com/styled-components/babel-plugin-styled-components/issues/77#issuecomment-321064668

**Comment by penx** [comment]
I would imagine Glamorous => emotion would be an easier process than Glamorous => styled-components, as emotion supports object notation.

Similarly, if we wanted to convert to styled components at a later date, this could be staged via:

1. Glamorous => emotion
2. emotion object => emotion template literal
3. emotion template literal => styled-components

(as each of those steps is a relatively small task, 2 is a little larger but wouldn't need to all be done in one go)

**Comment by penx** [comment]
@Loque- will be looking in to what is involved in moving from Glamorous to emotion with object notation

**Comment by penx** [comment]
`glamorous.span` is a shortcut for `glamorous("span")`, would expect emotion would provide similar shortcuts, else would be fairly easy to add these shortcuts.

Would be good to be able to script these changes so they could be done at any point.

**Comment by Loque-** [comment]
Nice spot, it certainly is but comes with a dependancy: https://emotion.sh/docs/styled#element-shorthand

I'm guessing due to how Glamorous is implemented this would be preferred, is that correct?

**Comment by penx** [comment]
For the initial port I would say we use it, could potentially phase it out over time

**Comment by stevesims** [comment]
looking at the code, we're using the shortcut `glamorous.span` (et al) 57 times in our code

those instances could be changed using a global regex search & replace
```glamorous\.(\w*)\(```
replace with:
```styled('$1')(```

**Comment by Loque-** [comment]
Thanks Steve,

I personally don't mind adding the dependancy for the moment and would leave is with the only change being `glamorous` to `styled` captured so far;
```
// Glamorous
const elemName = glamorous.span(({ bold, anotherOption }) => ({ ... }));

// Emotion
const elemName = styled.span(({ bold, anotherOption }) => ({ ... }));
```
