### ISSUE TITLE
viewBox on SVGBase

### ISSUE THREAD

**Issue by penx** [penx/govuk-react#238]
Why is the viewBox on SVGBase set to:

+      viewBox="-0.2 0 17 14"

?

**Comment by Loque-** [comment]
That will most likely be a mistake from an authors editor. I'll tidy this up quickly later unless you beat me to it.

**Comment by Loque-** [comment]
I doubt it will be a visible difference to be fair, or if so, just an improvement as I doubt any of the SVG's expected/depended on the negative top value of `-0.2`? Can you think of a good example to check after making the change?

**Comment by penx** [comment]
Looks like only ArrowLeft and ArrowRight use the SVGBase without setting a viewbox, so they're the only 2 to check. Just need to check if the edges of the vector are against the edges before and after.

I also wonder how they would behave without a viewBox set at all.. maybe SVGBase shouldn't set a default viewbox.

**Comment by Loque-** [comment]
I am in favour of removing the default but also ensuring SVG elements have their own viewbox property that is accurate.

For reference: https://www.sarasoueidan.com/blog/svg-coordinate-systems/
