### ISSUE TITLE
Should LoadingBox contain floats?

### ISSUE THREAD

**Issue by penx** [penx/govuk-react#239]
Should LoadingBox contain floats with an :after clearfix?

**Comment by Loque-** [comment]
I'm not sure why it would need to? It doesn't currently; https://github.com/penx/govuk-react/blob/master/components/loading-box/src/index.js

**Comment by penx** [comment]
Because if you have a load of floats, and you stick a LoadingBox around them, the LoadingBox won't completely cover the child elements. Instead you have to contain the floats in an element that clears them and then stick the LoadingBox around that. I can't think of any drawbacks to sticking a clearfix on the LoadingBox to prevent this, though it does mean it's not a totally transparent component (in the behaviour sense) when loading is false.

**Comment by penx** [comment]
The purpose of the loading box is to wrap other react components and cover them with an overlay + spinner icon if a boolean 'loading' is true, e.g.

```
  const loading = someCheck();
  return <LoadingBox loading={loading}>
    <H1>Lorem ipsum dolor sit amet</H1>
    <H2>Consectetur adipisicing elit. Quia incidunt, earum molestiae omnis labore adipisci.</H2>
  </LoadingBox>
```

**Comment by penx** [comment]
In the above example, if H1 and H2 were floats, I think I'd always expect LoadingBox to clear them

**Comment by Loque-** [comment]
I personally don't like that - if someone would like to float items they should be responsible for clearing the floats and add the clear to that specific instance of the `LoadingBox`, or add a container around the two floating items.

Maybe a middle ground would be to pass it as an option?

**Comment by Loque-** [comment]
Adding clearfix to every instance of `LoadingBox` would be mean every instance would have rendered an `:after` element with a `table`, just incase someone didn't clear their floats (naughty!).

**Comment by penx** [comment]
ok fair points, someone shouldn't be using a LoadingBox to do the clearing for them, and it adds processing overhead on the browser where likely not needed. Lets not do it :-)

**Comment by penx** [comment]
LoadingBox should be able to support a custom CSS class that allowed the parent component to set clearfix on the LoadingBox element, I think this is already supported.
