### ISSUE TITLE
Width, height and display:block on SVGBase

### ISSUE THREAD

**Issue by penx** [penx/govuk-react#243]
Should the width and height of the SVGBase be set to 100%?

And display: block set by default?

I have an issue where I'm trying to align an icon that's using SVGBase using `vertical-align: baseline`;

Unfortunately the icon grows to the height of the container, centering the vector in the vertical center, and not allowing me to line up the bottom of the icon with the bottom of the text.

**Comment by Loque-** [comment]
I personally think we should remove all of those attributes, including the x & y co-ordinates as they are not required by default.

It also looks like we don't need to include the version and xmlns: https://stackoverflow.com/a/18468348

**Comment by Loque-** [comment]
With all these elements removed, I think the only thing gained from having an SVG base component is to ensure a `version` property and `title` child element is added to SVG elements.
