### ISSUE TITLE
create own repo of govuk-react/icons

### ISSUE THREAD

**Issue by marksy** [penx/govuk-react#69]
split out icons into its own independent repo so can be used on other projects

**Comment by penx** [comment]
scoped as `@govuk-react/icons`

**Comment by penx** [comment]
now the project is a monorepo, we have a `@govuk-react/icons` package that will be published and can be used independently, so separating icons in to a separate repo may no longer be needed.

**Comment by penx** [comment]
@marksy should we close this?
